version: '3.8'

services:
  process-stream:
    build:
      context: .
      dockerfile: Dockerfile.receiveStream
    container_name: receive-stream
    ports:
      - "5000:5000"
    volumes:
      - ./scripts/receiveStream:/app/scripts
    environment:
      - CONTAINER_2_URL=http://azure-openai:5001/process
      - PYTHONUNBUFFERED=1  # Add this for better logging
    depends_on:
      - azure-openai
    networks:
      - chatterbox-network

  azure-openai:
    build:
      context: .
      dockerfile: Dockerfile.processStream
    container_name: process-stream
    ports:
      - "5001:5001"
    volumes:
      - ./scripts/processStream:/app/scripts
      - ./logs:/app/logs
    environment:
      - AZ_VISION_ENDPOINT=${AZ_VISION_ENDPOINT}
      - AZ_RESOURCE_KEY=${AZ_RESOURCE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1  # Add this for better logging
    depends_on:
      - socketio-server
    networks:
      - chatterbox-network

  socketio-server:
    build:
      context: .
      dockerfile: Dockerfile.publishMessage
    container_name: publish-message
    ports:
      - "5002:5002"
    volumes:
      - ./scripts/socketIO:/app/scripts/socketIO
      - ./logs:/app/logs
    environment:
      - SOCKETIO_PORT=5002
      - PYTHONUNBUFFERED=1  # Add this for better logging
    networks:
      - chatterbox-network

networks:
  chatterbox-network:
    driver: bridge